#!/usr/bin/env python3
"""
Step-by-step guide to find Gmail App Passwords
"""

def show_app_password_guide():
    print("🔍 Finding Gmail App Passwords - Step by Step Guide")
    print("=" * 60)
    print()
    
    print("📍 STEP 1: Check if 2-Factor Authentication is enabled")
    print("-" * 50)
    print("1. Go to: https://myaccount.google.com/")
    print("2. Click 'Security' on the left sidebar")
    print("3. Look for '2-Step Verification' section")
    print("4. It should say 'On' or 'Off'")
    print()
    print("❗ If it says 'Off', you MUST enable it first!")
    print("   App passwords only work with 2-Factor Auth enabled.")
    print()
    
    print("📍 STEP 2: Enable 2-Factor Authentication (if needed)")
    print("-" * 50)
    print("1. Click on '2-Step Verification'")
    print("2. Click 'Get started' or 'Turn on'")
    print("3. Follow the prompts (usually phone verification)")
    print("4. Complete the setup")
    print()
    
    print("📍 STEP 3: Find App Passwords")
    print("-" * 30)
    print("1. Go back to: https://myaccount.google.com/security")
    print("2. Look for 'App passwords' section")
    print("3. It might be under 'Signing in to Google'")
    print("4. OR search for 'App passwords' in the search box")
    print()
    print("🔍 Can't find 'App passwords'? Try these:")
    print("   • Direct link: https://myaccount.google.com/apppasswords")
    print("   • Search 'app passwords' in the Google Account search")
    print("   • Make sure 2-Step Verification is ON first")
    print()
    
    print("📍 STEP 4: Generate App Password")
    print("-" * 35)
    print("1. Click 'App passwords'")
    print("2. You might need to sign in again")
    print("3. Select app: 'Mail'")
    print("4. Select device: 'Other (Custom name)'")
    print("5. Type: 'Options Analyzer'")
    print("6. Click 'Generate'")
    print("7. Copy the 16-character password (looks like: abcd efgh ijkl mnop)")
    print()
    
    print("🆘 TROUBLESHOOTING:")
    print("-" * 20)
    print("❌ Don't see 'App passwords'?")
    print("   → 2-Step Verification must be ON first")
    print("   → Some Google Workspace accounts disable this feature")
    print("   → Try the direct link: https://myaccount.google.com/apppasswords")
    print()
    print("❌ Getting 'App passwords not available'?")
    print("   → Your account might use other security methods")
    print("   → Try disabling then re-enabling 2-Step Verification")
    print()
    print("❌ Still can't find it?")
    print("   → We have FREE alternatives! Use ntfy.sh instead")
    print("   → Run: python setup_sms.py and choose option 2 (ntfy.sh)")
    print()
    
    print("✅ ALTERNATIVE: Use ntfy.sh (Completely Free, No Gmail needed)")
    print("-" * 65)
    print("1. Download 'ntfy' app from App Store/Play Store")
    print("2. Choose a unique topic name (like 'arif_options_2024')")
    print("3. Subscribe to that topic in the app")
    print("4. Run: python setup_sms.py")
    print("5. Choose option 2 for ntfy.sh")
    print("6. No Gmail or passwords needed!")
    print()

if __name__ == "__main__":
    show_app_password_guide()
