#!/usr/bin/env python3
"""
Quick ntfy.sh setup - No Gmail needed!
"""

import requests
import time

def setup_ntfy():
    print("📱 Quick ntfy.sh Setup (FREE, No Gmail needed!)")
    print("=" * 55)
    print()
    
    print("🎯 What is ntfy.sh?")
    print("• Completely free push notification service")
    print("• No signup or registration required")
    print("• Works on phone and computer")
    print("• More reliable than email-to-SMS")
    print()
    
    print("📱 STEP 1: Install the app")
    print("-" * 25)
    print("1. Go to App Store (iPhone) or Play Store (Android)")
    print("2. Search for 'ntfy'")
    print("3. Install the app by 'Binwiederhier'")
    print("4. Open the app")
    print()
    
    print("🔧 STEP 2: Choose a topic")
    print("-" * 25)
    print("Think of a unique topic name (like a channel).")
    print("Examples:")
    print("• arif_options_2024")
    print("• my_stocks_alerts")
    print("• nvda_analysis_updates")
    print()
    
    topic = input("Enter your unique topic name: ").strip()
    
    if not topic:
        topic = "arif_options_2024"
        print(f"Using default: {topic}")
    
    print(f"\n📺 STEP 3: Subscribe in the app")
    print("-" * 30)
    print(f"1. In the ntfy app, tap the '+' button")
    print(f"2. Enter topic: {topic}")
    print(f"3. Tap 'Subscribe'")
    print(f"4. You'll see '{topic}' in your list")
    print()
    
    print("🧪 STEP 4: Test it!")
    print("-" * 18)
    print("I'll send a test notification now...")
    
    try:
        url = f"https://ntfy.sh/{topic}"
        response = requests.post(
            url,
            data=f"🎉 Welcome to ntfy.sh!\n\nYour Options Analyzer is ready to send you stock alerts to topic '{topic}'.\n\nThis is much easier than Gmail App passwords!",
            headers={
                'Title': '🧪 Test from Options Analyzer',
                'Priority': '3',
                'Tags': '📈,test'
            },
            timeout=10
        )
        
        if response.status_code == 200:
            print("✅ Test notification sent!")
            print("Check your ntfy app now!")
            print()
            
            received = input("Did you receive the notification in your ntfy app? (y/n): ").lower()
            
            if received == 'y':
                print("🎉 Perfect! ntfy.sh is working!")
                
                # Update config
                config_content = f'''# SMS Options Analyzer Configuration
# Generated by setup script

NOTIFICATION_CONFIG = {{'ntfy': {{'enabled': True, 'topic': '{topic}'}}}}

ANALYSIS_CONFIG = {{
    'ticker': 'AAPL',
    'price_range': 20.0,
    'schedule_interval': 'hour'
}}

NOTIFICATION_SETTINGS = {{
    'send_notifications': True,
    'notification_type': 'sms'
}}

LOG_CONFIG = {{
    'log_file': '/Users/mdarifuzzaman/Documents/puts/options_analyzer.log',
    'log_level': 'INFO'
}}
'''
                
                with open('/Users/mdarifuzzaman/Documents/puts/config.py', 'w') as f:
                    f.write(config_content)
                
                print(f"✅ Configuration updated with ntfy topic: {topic}")
                print()
                print("🚀 Ready to start!")
                print("Run: python sms_options_analyzer.py")
                print()
                
            else:
                print("❌ Notification not received. Let's troubleshoot:")
                print("1. Make sure you subscribed to the exact topic name")
                print(f"2. Topic should be: {topic}")
                print("3. Check your phone's notification settings")
                print("4. Try closing and reopening the ntfy app")
                
        else:
            print(f"❌ Failed to send test (HTTP {response.status_code})")
            
    except Exception as e:
        print(f"❌ Error sending test: {e}")
    
    print("\n💡 Why ntfy.sh is better:")
    print("• No Gmail setup needed")
    print("• No app passwords required")
    print("• Works instantly")
    print("• Completely free forever")
    print("• More reliable than email")

if __name__ == "__main__":
    setup_ntfy()
