# Render.com Configuration
# This file tells Render how to deploy your service

# Service Type: Background Worker (for scripts that run continuously)
# Build Command: pip install -r requirements.txt
# Start Command: python cloud_main.py

# Environment: Python 3.11
# Free Tier: 750 hours/month (enough for 24/7)

# The app will automatically:
# 1. Install Python dependencies
# 2. Start the options analyzer
# 3. Run hourly NVDA analysis
# 4. Send notifications to your phone via ntfy
